-- MySQL Script generated by MySQL Workbench
-- Tue Dec  3 20:56:37 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE=‘TRADITIONAL,ALLOW_INVALID_DATES’;
-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema South_Bronx_Vet
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema South_Bronx_Vet
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `South_Bronx_Vet` DEFAULT CHARACTER SET utf8 ;
USE `South_Bronx_Vet` ;
-- -----------------------------------------------------
-- Table `South_Bronx_Vet`.`Locations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `South_Bronx_Vet`.`Locations` (
  `Facility_Location_id` INT NOT NULL AUTO_INCREMENT,
  `Facility_Name` VARCHAR(255) NOT NULL,
  `Facility_Address` VARCHAR(255) NOT NULL,
  `Facility_City` VARCHAR(255) NOT NULL,
  `Facility_State` VARCHAR(255) NOT NULL,
  `Facility_Zip` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Facility_Location_id`),
  UNIQUE INDEX `Facility_Location_id_UNIQUE` (`Facility_Location_id` ASC),
  UNIQUE INDEX `Facility_Name_UNIQUE` (`Facility_Name` ASC))
ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `South_Bronx_Vet`.`Appointments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `South_Bronx_Vet`.`Appointments` (
  `Appointment_id` INT NOT NULL AUTO_INCREMENT,
  `Appointment_Type` VARCHAR(45) NOT NULL,
  `Appointment_Date` DATETIME NOT NULL,
  `Appointment_Duration` VARCHAR(45) NOT NULL,
  `Facility_Location_id` INT NOT NULL,
  `Location_Facility_Location_id` INT NOT NULL,
  PRIMARY KEY (`Appointment_id`, `Location_Facility_Location_id`),
  INDEX `fk_Visit_Location1_idx` (`Location_Facility_Location_id` ASC),
  CONSTRAINT `fk_Visit_Location1`
    FOREIGN KEY (`Location_Facility_Location_id`)
    REFERENCES `South_Bronx_Vet`.`Locations` (`Facility_Location_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `South_Bronx_Vet`.`Pet_Owners`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `South_Bronx_Vet`.`Pet_Owners` (
  `Pet_Owner_id` INT NOT NULL,
  `Pet_Owner_FirstName` VARCHAR(255) NOT NULL,
  `Pet_Owner_LastName` VARCHAR(255) NOT NULL,
  `Pet_Owner_Email` VARCHAR(255) NULL,
  `Pet_Owner_Phone` VARCHAR(45) NOT NULL,
  `Pet_Owner_Address` VARCHAR(255) NOT NULL,
  `Pet_Owner_City` VARCHAR(255) NOT NULL,
  `Pet_Owner_State` VARCHAR(45) NOT NULL,
  `Pet_Owner_ZipCode` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Pet_Owner_id`))
ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `South_Bronx_Vet`.`Pets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `South_Bronx_Vet`.`Pets` (
  `Pet_id` INT NOT NULL AUTO_INCREMENT,
  `Pet_FirstName` VARCHAR(255) NOT NULL,
  `Pet_LastName` VARCHAR(255) NOT NULL,
  `Pet_Type` VARCHAR(255) NOT NULL,
  `Pet_Gender` VARCHAR(255) NOT NULL,
  `Pet_Owner_id` INT NOT NULL,
  `Employee_id` INT NOT NULL,
  `Facility_Location_id` INT NOT NULL,
  `Appointment_id` INT NOT NULL,
  `Pet_Owner_Pet_Owner_id` INT NOT NULL,
  PRIMARY KEY (`Pet_id`),
  INDEX `fk_Pet_Visit1_idx` (`Appointment_id` ASC),
  INDEX `fk_Pet_Location1_idx` (`Facility_Location_id` ASC),
  INDEX `fk_Pet_Pet_Owner1_idx` (`Pet_Owner_Pet_Owner_id` ASC),
  CONSTRAINT `fk_Pet_Visit1`
    FOREIGN KEY (`Appointment_id`)
    REFERENCES `South_Bronx_Vet`.`Appointments` (`Appointment_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pet_Location1`
    FOREIGN KEY (`Facility_Location_id`)
    REFERENCES `South_Bronx_Vet`.`Locations` (`Facility_Location_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pet_Pet_Owner1`
    FOREIGN KEY (`Pet_Owner_Pet_Owner_id`)
    REFERENCES `South_Bronx_Vet`.`Pet_Owners` (`Pet_Owner_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `South_Bronx_Vet`.`Medications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `South_Bronx_Vet`.`Medications` (
  `Drug_id` INT NOT NULL AUTO_INCREMENT,
  `Drug_Name` VARCHAR(255) NOT NULL,
  `Doctor_id` INT NOT NULL,
  `Drug_Instructions` VARCHAR(255) NOT NULL,
  `Date_Prescribed` DATETIME NOT NULL,
  `Pet_id` INT NOT NULL,
  `Facility_Location_id` INT NOT NULL,
  `Medication_Expiration_Date` DATETIME NOT NULL,
  `Drug_Stock_Date` DATETIME NOT NULL,
  `Drug_Stock_Qty` INT NOT NULL,
  `Location_Facility_Location_id` INT NOT NULL,
  `Pets_Pet_id` INT NOT NULL,
  PRIMARY KEY (`Drug_id`, `Location_Facility_Location_id`),
  INDEX `fk_Medication_Location1_idx` (`Location_Facility_Location_id` ASC),
  INDEX `fk_Medications_Pets1_idx` (`Pets_Pet_id` ASC),
  CONSTRAINT `fk_Medication_Location1`
    FOREIGN KEY (`Location_Facility_Location_id`)
    REFERENCES `South_Bronx_Vet`.`Locations` (`Facility_Location_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Medications_Pets1`
    FOREIGN KEY (`Pets_Pet_id`)
    REFERENCES `South_Bronx_Vet`.`Pets` (`Pet_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `South_Bronx_Vet`.`Employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `South_Bronx_Vet`.`Employees` (
  `Employee_id` INT NOT NULL AUTO_INCREMENT,
  `Is_Doctor` VARCHAR(45) NOT NULL,
  `Employee_Type` VARCHAR(255) NOT NULL,
  `Employee_FirstName` VARCHAR(255) NOT NULL,
  `Employee_LastName` VARCHAR(255) NOT NULL,
  `Employee_MiddleName` VARCHAR(255) NULL,
  `Employee_UserName` VARCHAR(255) NOT NULL,
  `Employee_Password` VARCHAR(255) NOT NULL,
  `Pet_id` INT NULL,
  `Facility_Location_id` INT NOT NULL,
  `Location_Facility_Location_id` INT NOT NULL,
  `Pet_Pet_id` INT NOT NULL,
  PRIMARY KEY (`Employee_id`),
  UNIQUE INDEX `Employee_Password_UNIQUE` (`Employee_Password` ASC),
  UNIQUE INDEX `Employee_UserName_UNIQUE` (`Employee_UserName` ASC),
  INDEX `fk_Employee_Location1_idx` (`Location_Facility_Location_id` ASC),
  INDEX `fk_Employee_Pet1_idx` (`Pet_Pet_id` ASC),
  CONSTRAINT `fk_Employee_Location1`
    FOREIGN KEY (`Location_Facility_Location_id`)
    REFERENCES `South_Bronx_Vet`.`Locations` (`Facility_Location_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Employee_Pet1`
    FOREIGN KEY (`Pet_Pet_id`)
    REFERENCES `South_Bronx_Vet`.`Pets` (`Pet_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;